# Generated by Django 3.2.4 on 2025-03-25 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=255)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('text_generation', 'Генерация текста'), ('text_ready', 'Текст сгенерирован'), ('melody_generation', 'Создание мелодии'), ('melody_ready', 'Мелодия готова'), ('error', 'Ошибка')], default='text_generation', max_length=50)),
                ('track_stream_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
