# Generated by Django 3.2.4 on 2025-03-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_generationtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='track',
            name='image',
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
