# Generated by Django 3.2.4 on 2025-03-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_track_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('pop', 'Поп'), ('rock', 'Рок'), ('electronic', 'Электронная'), ('hiphop', 'Хип-хоп')], max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='mood',
            field=models.CharField(choices=[('energetic', 'Энергичное'), ('calm', 'Спокойное'), ('dreamy', 'Мечтательное'), ('sad', 'Грустное')], max_length=100),
        ),
    ]
