# Generated by Django 3.2.4 on 2025-03-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_auto_20250326_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
