# Generated by Django 3.2.4 on 2025-03-26 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
